language: python
python:
  - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure.
sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/BuzzerExample
  - PLATFORMIO_CI_SRC=examples/DimmableLightExample
  - PLATFORMIO_CI_SRC=examples/DoorContactExample
  - PLATFORMIO_CI_SRC=examples/DS6120SensorExample
  - PLATFORMIO_CI_SRC=examples/L298MotorControlExample
  - PLATFORMIO_CI_SRC=examples/LEDExample
  - PLATFORMIO_CI_SRC=examples/RelayExample
  - PLATFORMIO_CI_SRC=examples/ToggleSwitchExample
  - PLATFORMIO_CI_SRC=examples/REXExample
  - PLATFORMIO_CI_SRC=examples/ResetManagerExample
  - PLATFORMIO_CI_SRC=examples/TemperatureConversionExample
  - PLATFORMIO_CI_SRC=examples/TemperatureSensorExample
  - PLATFORMIO_CI_SRC=examples/PIRExample

install:
  # - pip install -U cpplint
  - pip install -U platformio
  - pio update

before_script:
  - env
  - echo $HOME
  - echo $TRAVIS_BUILD_DIR
  - ls -al $PWD

script:
  # - cpplint --repository=. --recursive --linelength=200 --filter=-build/include  ./
  - make all

notifications:
  email:
    on_success: change
    on_failure: change
